// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe717WXiXOvc4HNQlxtDCIeHXs1Qm35P8',
    appId: '1:95380890504:web:b504bd345620d65ed5103d',
    messagingSenderId: '95380890504',
    projectId: 'course-app-3423b',
    authDomain: 'course-app-3423b.firebaseapp.com',
    databaseURL: 'https://course-app-3423b-default-rtdb.firebaseio.com',
    storageBucket: 'course-app-3423b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDDTNLjfU0hkGoMOMdgFfql8tS_A9Aax8',
    appId: '1:95380890504:android:38aa50c2ebd56d22d5103d',
    messagingSenderId: '95380890504',
    projectId: 'course-app-3423b',
    databaseURL: 'https://course-app-3423b-default-rtdb.firebaseio.com',
    storageBucket: 'course-app-3423b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxIQXXhXQV4D03DYejqlvZzI-PXAKYAg',
    appId: '1:95380890504:ios:48f3ab77e6b0bb6fd5103d',
    messagingSenderId: '95380890504',
    projectId: 'course-app-3423b',
    databaseURL: 'https://course-app-3423b-default-rtdb.firebaseio.com',
    storageBucket: 'course-app-3423b.appspot.com',
    iosBundleId: 'com.example.courseApp',
  );
}
